name: test2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  circular_countdown_timer: ^0.2.3
  flutter:
    sdk: flutter
  flutter_timer_countdown: ^1.0.7
  icalendar_parser: ^2.0.0
  rflutter_alert: ^2.0.7
  syncfusion_flutter_calendar: ^25.1.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFA500"
  adaptive_icon_foreground: assets/logo_foreground.png

flutter:
  uses-material-design: true
